version: '3.8'
services:
  client:
    build:
      context: client/
    ports:
      - "4200:4200"
     
    container_name: ssgaikwad/emartclient
    restart: always
    depends_on:
      # - webapi
      - api
  
  webapi:
    build:
      context: javaapi/
    ports:
      - "9000:9000"
    container_name: ssgaikwad/emartwebapi
     
    restart: always
    depends_on:
      - emartdb
      
  
  api:
    build:
      context:  nodeapi/
    ports:
      - "5000:5000"
    container_name: ssgaikwad/emartapi
    restart: always
    depends_on:
      - emongo
  
  nginx:
    image: nginx
    ports:
      - "80:80"
    container_name: ssgaikwad/emartnginx
    
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  
  emartdb:
    image: mysql:8
    ports:
      - "3306:3306"
    container_name: emartdb-container
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MY_DB_PASS}
      - MYSQL_DATABASE=books

  emongo:
    image: mongo:5
    ports:
      - "27017:27017"
    container_name: emongo-container
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=epoc
